# Site settings
title: LinkedPipes ETL
email: klimek@opendata.cz
description: > # this means to ignore newlines until "baseurl:"
  Web presentation of LinkedPipes, a suite of open-source software for Linked Data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://etl.linkedpipes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

sass:
    sass_dir: _sass
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap